### ISSUE TITLE
Fatal error: Class 'WP_Widget' not found

### ISSUE THREAD

**Issue by pippinsplugins** [AffiliateWP/affwp-docs#9]
I'm seeing a fatal error when running the generator:
![screen shot 2016-05-25 at 1 29 05 pm](https://cloud.githubusercontent.com/assets/1034109/15551680/b8ad796c-227c-11e6-9752-9f45d8370296.png)

It's coming from EDD but I'm not sure it's an EDD bug. Any reason you can think of that WP core files wouldn't be loaded?

**Comment by ramiabraham** [comment]
Well that's weird. Tried updating composer? Crapshoot but who knows

**Comment by pippinsplugins** [comment]
If I remove EDD, I get a similar error:

Fatal error: Class 'WP_Widget' not found in /Users/pippin/Sites/edd/wp-includes/widgets/class-wp-widget-pages.php on line 17

**Comment by ramiabraham** [comment]
Ah ok - wp-cli needs to be updated it looks like. See: https://github.com/wp-cli/wp-cli/issues/2284, https://github.com/wp-cli/wp-cli/issues/2291

**Comment by pippinsplugins** [comment]
There we go!
